### ISSUE TITLE
Soundness issue: writing to an `as_ptr` pointer is UB

### ISSUE THREAD

**Issue by RalfJung** [LiosK/fstr-rs#1]
I stumbled upon this code in this crate:

https://github.com/LiosK/fstr-rs/blob/0b4a359880138d99a66949ae29e95c5b19810670/src/lib.rs#L253

That line has Undefined Behavior: `inner.as_ptr()` is an immutable pointer, writing to it is not allowed.

**Comment by LiosK** [comment]
Thank you!
